coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
        base: auto

comment:
  layout: 'diff, components, files'
  behavior: default

component_management:
  default_rules:
    statuses:
      - target: auto
  individual_components:
    - component_id: debug-adapter
      name: Debugger
      path: packages/debug-adapter/
    - component_id: client
      name: Extension Client
      path: packages/client/
    - component_id: lsp-server
      name: LSP Server
      path: packages/server/
