flag_management:
  individual_flags:
    - name: debug-adapter
      paths: 
      - packages/debug-adapter
    - name: lsp-ide-server
      paths: 
      - packages/server
    - name: lsp-ide-client
      paths: 
      - packages/client