# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push: 
    branches:
      - master
  pull_request:


jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-latest] # [windows-latest, ubuntu-latest, macos-latest]
            node-version: [lts/gallium]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run compile
    # - name: Run headless test
    #   uses: smithki/xvfb-action@v1.1.2
    #   with:
    #     run: npm run test:e2e
    #     options: --disable-features=NetworkService --disable-gpu
    - run: npm test
    - name: Unit Tests
      run: npm run test:unit
    # - name: Contribute List
    #   # if: matrix.os == 'ubuntu-latest'
    #   uses: akhilmhdh/contributors-readme-action@v2.3.6
    #   with:
    #     image_size: 100
    #     auto_detect_branch_protection: true
    #   env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
